### ISSUE TITLE
点击问题

### ISSUE THREAD

**Issue by jianghaijun** [Moosphan/Material-BottomBarLayout#1]
发现一个问题，当我快速，同时点击两个图标时 界面会一直闪烁，就卡死了。这个问题能解决一下么？

**Comment by Moosphan** [comment]
@jianghaijun 抱歉这么晚才回复，我刚刚测试了一下，没有该问题。我觉得出现该问题的原因不是在于bottombarlayout，而是在于fragment之间的切换没有处理好，如果不是，麻烦贴一下核心代码。再次谢谢您的反馈
